---
 
---

## What is a data package?

A data package is a collection of data files and metadata files that describe the data.  

There are two equally important parts that make up a data package: _data_ and _metadata_.  
We will get into more details on these components in this lesson.  

===

## Why package and publish your data?  

1. Data is a valuable asset

2. Efficient collaboration

3. Credit for your work 

4. Funder requirement

5. Publisher requirement

6. Open, Reproducible Science

===

## Integrating data documentation 

It is important to incorporate documentation of your data throughout your reproducible research pipeline.  


1. Aquire raw data from online repository.

   - __Download metadata if it's available.__

2. Extract, transform, and load data into storage for analysis.

   - __Create metadata, and document your data transformations in your scripts.__

3. Perform data analysis (e.g. model inference) and visualization.

   - __Script your data -> visuals process.__

4. Update documentation and reports.

   - __Revise metadata for your derived data.__ 

5. Publish results, including reports, data and code/software.
 
   - __Publish your data package (metadata + data + scripts)!__


===

## Goals of data packaging

1. Improve sharing data with collaborators now.

2. Easily publish your data now or in the future. 

