---

---

## What is Metadata?

Metadata is the information needed for someone else to understand and use your data.  

This include package-level _and_ file-level

===

### Metadata Standards

The goal is to have a machine and human readable description of your data. 

This can again mean using a controlled set of descriptors for your data specified by the standard. 

There are several metadata standards, and those standards can vary between disciplines
and types of data.  

   - General: [Dublin Core]: http://dublincore.org/
   - Ecological/Environmental/Biological: [EML]: https://knb.ecoinformatics.org/external//emlparser/docs/index.html, [Darwin Core]: https://dwc.tdwg.org/
   - Social science: [DDI]: http://www.ddialliance.org/, [EAD]: https://www.loc.gov/ead/ 
   - Geospatial/Meterological/Oceanographic: ISO 19115, FGDC/CSDGM (no longer current)

===

### Common components of metadata

Package-level:
 - Geographic area of data (generally)
 - Data creator
 - Funding source

File-level:
 - Define variable names
 - Describe variables (units, etc.)
 - Define allowed values for a variable
 - Define units for variable

===

### Creating metadata

Employer-specific methods (ex: USGS)

Repository-specific methods

   GUI for a repository - show pretty picture here: 

   R packages (EML, dataspice)






  
