---

---

## Publishing your data

Choosing to publish your data products in a long-term repository can:

   - fulfill a journal requirement to publish data
   - facilitate citing your dataset by assigning a permanent uniquely identifiable code (DOI)
   - improve discovery of and access to your dataset for others
   - enable re-use and greater visibility of your work

===

### Get an ORCiD 
 
ORCiDs identify you and link you to your publications and research products.  They are used by journals, repositories, etc. and often as a log in.  To obtain an ORCiD, register at [https://orcid.org]: https://orcid.org.

===

### Picking a repository 

There are many repositories out there, and it can seem overwhelming picking a suitable one for your data. 

Repositories can be subject or domain specific.  [re3data]: https://www.re3data.org/ lists repositories by subject and can help you pick an appropriate repository for your data.  

===

[DataONE]: https://www.dataone.org/ is a federation of repositories housing many different types of data.  Some of these repositories include Knowledge Network for Biocomplexity[(KNB)]: https://knb.ecoinformatics.org/, Environmental Data Initiative [(EDI)]: https://environmentaldatainitiative.org/, [Dryad]: https://datadryad.org/, [USGS Science Data Catalog]: https://data.usgs.gov/datacatalog/

For qualitative data, there are a few dedicated repositories: [QDR]: https://qdr.syr.edu/, [Data-PASS]: http://data-pass.org/

===

Though a bit different, [Zenodo]: https://zenodo.org/ facilitates publishing (with a DOI) and archiving all research outputs from all research fields.  This can be used to publish releases of your code that lives in a GitHub repository.  However, since GitHub is not designed for data storage and is not a persistent repository, this is not a recommended way to store or publish data.  

===


 
Uploading requirements

Uploading data and metadata - check to see if you can just upload a metadata file...will the repo "see" the metadata?

Embargoing - controlling access

Getting a DOI

Citation

Version unique ids for datasets - mention this




rdataone R package


